auth:
  active: true
  url: "http://172.17.254.189:9999"
  realm: "basyx"
  clientId: "basyx-client"
  tokenUrl: "http://172.17.254.189:9999/realms/basyx/protocol/openid-connect/token"
  authUrl: "http://172.17.254.189:9999/realms/basyx/protocol/openid-connect/auth"
  authFlow: "code"
  scope: "openid profile email"

security:
  enabled: true
  type: "oauth2"
  authFlow: "code"
  oauth2Host: "http://172.17.254.189:9999/realms/basyx"
  clientId: "basyx-client"
  tokenUrl: "http://172.17.254.189:9999/realms/basyx/protocol/openid-connect/token"
  authUrl: "http://172.17.254.189:9999/realms/basyx/protocol/openid-connect/auth"
  scope: "openid profile email"

keycloakFeatureControl: true
keycloakFeatureControlRolePrefix: ""

aasRepository: "http://172.17.254.189"
submodelRepository: "http://172.17.254.189"
conceptDescriptionRepository: "http://172.17.254.189"
aasRegistry: "http://172.17.254.189:8083"
submodelRegistry: "http://172.17.254.189:8084"