events
{
    worker_connections 1024;
}

http
{
    upstream aas_backend 
    {
        server machine1-aas:8081;
        server machine2-aas:8081;
    }

    # HTTP (80) Server
    server
    {
        listen 80;
        server_name localhost;
        client_max_body_size 100M;

        location / 
        {
            proxy_pass http://aas_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # HTTPS (443) Server
    server
    {
        listen 443 ssl;
        server_name localhost;
        client_max_body_size 100M;

        ssl_certificate     /etc/nginx/certs/certificate.crt;
        ssl_certificate_key /etc/nginx/certs/private.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / 
        {
            proxy_pass http://aas_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
